In [1]:
# First, import PyTorch
import torch

In [2]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [3]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

In [4]:
# Features are 5 random normal variables
features = torch.randn((1, 5))

In [5]:
features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [6]:
# True weights for our data, random normal variables again
weights = torch.randn_like(features)

In [7]:
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [8]:
bias = torch.randn((1, 1))

In [9]:
bias

tensor([[0.3177]])

In [10]:
y = activation(torch.sum(features * weights) + bias)

In [11]:
y

tensor([[0.1595]])

In [12]:
y = activation((features * weights).sum() + bias)

In [13]:
y

tensor([[0.1595]])

In [14]:
y = activation(torch.mm(features, weights.view(5,1)) + bias)

In [15]:
y

tensor([[0.1595]])

# Multiple Layers

In [16]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

In [17]:
# Features are 3 random normal variables
features = torch.randn((1, 3))

In [18]:
# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

In [19]:
# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

In [20]:
# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [21]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])
